import type { Course } from '@/interfaces/course'

export const data: Array<Course> = [
  {
    id: 1,
    cover: '/images/courses/a9e7b27a0c5e986a22416d79e2e9dba9.jpg',
    title: 'Graphic Designing',
    rating: 5,
    ratingCount: 42,
    price: 0,
    category: 'Digital Skills',
  },
  {
    id: 2,
    cover: '/images/courses/alvaro-reyes-qWwpHwip31M-unsplash.jpg',
    title: 'Digital Marketing',
    rating: 5,
    ratingCount: 38,
    price: 0,
    category: 'Digital Skills',
  },
  {
    id: 3,
    cover: '/images/courses/christopher-gower-m_HRfLhgABo-unsplash.jpg',
    title: 'Web Development',
    rating: 5,
    ratingCount: 51,
    price: 0,
    category: 'Digital Skills',
  },
  {
    id: 4,
    cover: '/images/courses/true-agency-o4UhdLv5jbQ-unsplash.jpg',
    title: 'App Development',
    rating: 5,
    ratingCount: 29,
    price: 0,
    category: 'Digital Skills',
  },
  {
    id: 5,
    cover: '/images/courses/stillness-inmotion-Jh6aQX-25Uo-unsplash.jpg',
    title: 'AI Programming',
    rating: 5,
    ratingCount: 34,
    price: 0,
    category: 'Digital Skills',
  },
  {
    id: 6,
    cover: '/images/courses/stillness-inmotion-YSCCnRGrD-4-unsplash.jpg',
    title: 'Youtube Automation',
    rating: 4,
    ratingCount: 27,
    price: 0,
    category: 'Digital Skills',
  },
  {
    id: 7,
    cover: '/images/courses/grovemade-RvPDe41lYBA-unsplash.jpg',
    title: 'Freelancing',
    rating: 5,
    ratingCount: 46,
    price: 0,
    category: 'Digital Skills',
  },
  {
    id: 8,
    cover: '/images/courses/a9e7b27a0c5e986a22416d79e2e9dba9.jpg',
    title: 'Basic Computer',
    rating: 5,
    ratingCount: 61,
    price: 0,
    category: 'Digital Skills',
  },
  {
    id: 9,
    cover: '/images/courses/alvaro-reyes-qWwpHwip31M-unsplash.jpg',
    title: "Oxford's Advanced Spoken English",
    rating: 5,
    ratingCount: 55,
    price: 0,
    category: 'Language',
  },
  {
    id: 10,
    cover: '/images/courses/christopher-gower-m_HRfLhgABo-unsplash.jpg',
    title: 'IELTS / PTE Preparation',
    rating: 5,
    ratingCount: 48,
    price: 0,
    category: 'Language',
  },
]
